### DISCUSSION TITLE
Allow changing z-index in custom theming

### DISCUSSION THREAD

**Discussion by arcoraven** [rainbow-me/rainbowkit#1114] [Ideas]
**Problem**
The RainbowKit modal sets a z-index of 2147483646.

**Use case**
I'm building a custom connector that pops up a modal with the exact same z-index, but RainbowKit shows up on top because it's later in the DOM.

**Proposed solution**
Allow setting a `zIndex` prop in a custom theme so I can lower it as needed.

Right now this is my workaround:
```css
[data-rk] [aria-labelledby="rk_connect_title"] {
  z-index: 2147483645 !important;
}
```
