### DISCUSSION TITLE
Info: How to change the ConnectButton Styling

### DISCUSSION THREAD

**Discussion by 0xKurt** [rainbow-me/rainbowkit#1465] [General]
Just like many others i encountered the problem that the `ConnectButton` styling can not be simply changed.
Only way is a customized button and that's pretty painful.
After some experiments i found out that you can utilize the `ju367v7o` CSS class to style the `ConnectButton` without destroying the whole modal design. It's a pretty dirty approach, but it works.

Example:

```css
.ju367v7o {
  font-weight: 500 !important;
  font-size: 1rem !important;
  letter-spacing: 0.05em;

  color: rgba(255, 255, 255, 0.85) !important;

  padding: 8px 25px !important;
  height: auto !important;

  box-shadow: 0 0 5px rgba(229, 223, 232, 0.3) !important;
  background: linear-gradient(0deg, #5e2374 0%, #ad33cc 100%) !important;

  border-radius: 5px !important;
}
```

Note: It's necessary to declare everything as important to overwrite the original values.

My styled `ConnectButton`:
![image](https://github.com/rainbow-me/rainbowkit/assets/22886639/9a94698b-cca1-45f5-b89f-490afcd9ba01)

All other styling is untouched:
![image](https://github.com/rainbow-me/rainbowkit/assets/22886639/8fce7f86-983e-48a2-830a-72cdc1413787)

![image](https://github.com/rainbow-me/rainbowkit/assets/22886639/dabda6aa-6a3b-44ce-9114-056c6dca9d4f)

![image](https://github.com/rainbow-me/rainbowkit/assets/22886639/12257998-4a2f-4d13-a2e0-9b3e1bd44017)

![image](https://github.com/rainbow-me/rainbowkit/assets/22886639/39f9b82d-0b82-4993-aae7-459d460e2b0d)

#590 #1117
