### ISSUE TITLE
[bug] TailwindCSS injected style break <ConnectButton/> styling

### ISSUE THREAD

**Issue by MatteoGauthier** [rainbow-me/rainbowkit#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### RainbowKit Version

0.1.0

### wagmi Version

0.3.3

### Current Behavior

<img width="518" alt="Capture d’écran 2022-05-06 à 11 56 59" src="https://user-images.githubusercontent.com/32040951/167110184-aa979979-2ee2-4151-b6c8-08e38839bfba.png">

### Expected Behavior

<img width="506" alt="Capture d’écran 2022-05-06 à 11 57 16" src="https://user-images.githubusercontent.com/32040951/167110194-f593b7a7-ecb9-42f5-afc6-9fb44106490f.png">

### Steps To Reproduce

- Add tailwindcss to the project

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/great-moon-9l6swr

**Comment by peterferguson** [comment]
This is due to tailwinds [preflight](https://tailwindcss.com/docs/preflight) styles. 

You can fix it by setting the following in your `tailwind.config.js` file
```js

module.exports = {
  ...,
  corePlugins: {
    preflight: false,
  },
  ...
}
```

and then importing an [altered preflight source](https://unpkg.com/tailwindcss@3.0.18/src/css/preflight.css) into your `global.css` as follows:

```css
@tailwind base;
@import './tw-preflight';
@tailwind components;
@tailwind utilities;
```

where the `tw-preflight.css` contains the already mentioned preflight source with the `background-color: transparent` removed
<details>

<summary>Like this</summary>

```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-color: transparent; /* 2 */
  background-image: none; /* 2 */
}
```

becomes

```css
/*
1. Correct the inability to style clickable types in iOS and Safari.
2. Remove default button styles.
*/

button,
[type='button'],
[type='reset'],
[type='submit'] {
  -webkit-appearance: button; /* 1 */
  background-image: none; /* 2 */
}
```
</details>

Problem is now you will need to explicitly set the `background-color` of all your other background-less buttons to be `transparent`.
